// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// formatFunc is an autogenerated mock type for the formatFunc type
type formatFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *formatFunc) Execute(_a0 float64) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(float64) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// newFormatFunc creates a new instance of formatFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFormatFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *formatFunc {
	mock := &formatFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
