// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Number is an autogenerated mock type for the Number type
type Number struct {
	mock.Mock
}

// NewNumber creates a new instance of Number. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNumber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Number {
	mock := &Number{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
